name: Build
on: 
  push: 
    branches:
      -master
  pull_request:
    branches:
      -master

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1 
        with:
          node-version: '14'  

      - name: Setup truffle
        run: |
         npm install -g truffle

      - name: Compile smart contracts
        run: |
         truffle compile
